/*
 * Oktawave KaaS API
 *
 * Oktawave KaaS API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type K44sInstanceType struct {
	Id float32 `json:"Id"`
	Label string `json:"Label"`
}
