/*
 * Oktawave KaaS API
 *
 * Oktawave KaaS API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IaasDictionaryEntry struct {
	Id float64 `json:"Id"`
	Label string `json:"Label"`
}
