/*
 * Oktawave KaaS API
 *
 * Oktawave KaaS API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type K44SClusterDetailsDto struct {
	Name string `json:"name"`
	CreationDate *Date `json:"creationDate"`
	Running bool `json:"running"`
	Version string `json:"version"`
}
