/*
 * Oktawave KaaS API
 *
 * Oktawave KaaS API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type IaasTicket struct {
	Id float64 `json:"Id"`
	CreationDate time.Time `json:"CreationDate"`
	EndDate time.Time `json:"EndDate"`
	Status *IaasDictionaryEntry `json:"Status"`
	OperationType *IaasDictionaryEntry `json:"OperationType"`
	ObjectId float64 `json:"ObjectId"`
	ObjectName string `json:"ObjectName"`
	Progress float64 `json:"Progress"`
}
