/*
 * Oktawave KaaS API
 *
 * Oktawave KaaS API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type K44SNodesList struct {
	// List of nodes(instances) to remove from cluster.
	InstancesIds []float32 `json:"instancesIds"`
}
