/*
 * Oktawave KaaS API
 *
 * Oktawave KaaS API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type K44sInstance struct {
	Id float64 `json:"Id"`
	Name string `json:"Name"`
	CreationDate time.Time `json:"CreationDate"`
	Subregion *K44sInstanceSubregion `json:"Subregion"`
	Type_ *K44sInstanceType `json:"Type"`
	Status *K44sInstanceStatus `json:"Status"`
	IpAddress string `json:"IpAddress"`
	TotalDisksCapacity float64 `json:"TotalDisksCapacity"`
	CpuNumber float64 `json:"CpuNumber"`
	RamMb float64 `json:"RamMb"`
}
