/*
 * Oktawave KaaS API
 *
 * Oktawave KaaS API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type K44sTaskDto struct {
	TaskId string `json:"taskId"`
	Operation string `json:"operation"`
	InstanceName string `json:"instanceName"`
	SubregionId float32 `json:"subregionId"`
	TypeId float32 `json:"typeId"`
	InstanceId float32 `json:"instanceId"`
	StartTime float32 `json:"startTime"`
	Status string `json:"status"`
}
