/*
 * Oktawave KaaS API
 *
 * Oktawave KaaS API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Node struct {
	// Subregion where the instance is placed.
	Subregion float32 `json:"subregion"`
	// Type of the instance. Represents CPU and Memory parameters for instance.
	Type_ float32 `json:"type"`
}
